Feature/face generation script
pkrucz00/MP2023 pull request #1
Opened 2023-03-17 08:18 UTC by pkrucz00

What has been done:
 - the basic (pretty much POC) script that opens, clicks over the game, generates faces and their DNAs then shuts the game.
 - a small set of 10 faces and DNAs were generated as an example
 - simple CLI

What should be discussed:
  - should all the people be bold?

What can be done:
  - the faces from different countries have different randomization spectra - the characters generated with "random" button look different than those in Spain, Poland, Sweden or Asia. For now "Poland" is hardcoded. We need a way of mittigating that.
  - choosing different sexes
  - smaller waiting times between positioning th mouse and clicking it

2023-03-25 15:52 UTC, czyjtu requested changes

2023-03-25 15:52 UTC, czyjtu commented on generate_faces.py
> +        click_random_dna()
looking for button location every iteration adds significant overhead. Maybe we can assume that window location will not change during the data collection phase?

2023-03-25 15:52 UTC, czyjtu commented on generate_faces.py
> +    time.sleep(1)
why?

2023-03-25 15:52 UTC, czyjtu commented on generate_faces.py
> +    main()
passing arguments through command-line would be useful (https://docs.python.org/3/library/argparse.html).

2023-03-25 15:52 UTC, czyjtu commented on generate_faces.py
> +        model_name = f"{randint(0, 1_000_000)}"
`randint` is fine, but `datetime.now` string looks better IMO

2023-03-25 15:52 UTC, czyjtu commented on generate_faces.py
> +    wait_and_click("locate_pics/randomize.png", label="Random", wait_in_sec=3)
Why do we have to wait so long?

2023-03-25 15:52 UTC, czyjtu commented on generate_faces.py
> +    main()
done with click

2023-03-26 12:31 UTC, pkrucz00 commented on generate_faces.py
> +        model_name = f"{randint(0, 1_000_000)}"
Changed it

2023-03-26 12:31 UTC, pkrucz00 commented on generate_faces.py
> +    wait_and_click("locate_pics/randomize.png", label="Random", wait_in_sec=3)
The time has been reduced to 0.01 s and the script seems to work properly. I'll try to lower it even further, but I think it is enoug for now.

2023-03-26 12:31 UTC, pkrucz00 commented on generate_faces.py
> +    time.sleep(1)
Using the default function that moved the cursor and immediatly clicked the button was not working properly. GUI sometimes was still focused on the previous button and clicked that instead, which in turn broke the flow of the script. A small wait time (0.05 sec for now but probably less in future) is necessary for it to work properly.

2023-03-26 15:04 UTC, pkrucz00 commented
What's changed:
   - applying suggested changes (including optimisation)
   - adding more diverce data generation by using choosing multiple sexes and ethnicities 
   - generation time measurement added
   - flag for archiving the results have been added

2023-05-23 12:47 UTC, merged